# Generated by Django 4.1.6 on 2023-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("itshop", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=300),
        ),
    ]
